export const DeviceStaticStatusBar = [
  {
    signature: 'core.parlar.ReadonlyBool.freezer_door',
    icon: 'opendoor',
    text: 'Freezer Door',
    toggle: false,
  },
  {
    signature: 'core.parlar.ReadonlyBool.fridge_door',
    icon: 'opendoor',
    text: 'Fridge Door',
    toggle: false,
  },
  {
    signature: 'core.parlar.ToggleableBool.lock',
    icon: 'lock',
    text: 'Lock',
    toggle: false,
  },
  {
    signature: 'core.parlar.ToggleableBool.mute',
    icon: 'mute',
    text: 'Mute',
    toggle: false,
  },
  {
    signature: 'core.parlar.ToggleableBool.super',
    icon: 'superfrost',
    text: 'Super Frost',
    toggle: false,
  },
  {
    signature: 'core.parlar.ToggleableBool.eco',
    icon: 'eco',
    text: 'Eco',
    toggle: false,
  },

  {
    signature: 'core.parlar.ToggleableBool.ice_maker',
    icon: 'icemaker',
    text: 'Ice Off',
    toggle: false,
  },
];

export const Placeholder =
  '/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCAJYAysDASIAAhEBAxEB/8QAGwABAAMBAQEBAAAAAAAAAAAAAAQFBgIDAQn/xAA8EAEAAQIDAQ0HAwMEAwAAAAAAAQIDBAUGERIVITE0NVFUcpGxwdETFiJBU2FzMnHwQoHhFCMzUkOh8f/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwD9uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjK8JTj8xs2aqqqabk7JmOOOCUdN05z7he35SC59w7PWL3dHoe4dnrF7uj0emssdewNixNm5VbmqqYnc/PgUO/+O61e7wXXuHZ6xe7o9D3Ds9Yvd0eil3/x3Wr3eb/47rV7vBde4dnrF7uj0PcOz1i93R6KXf8Ax3Wr3eb/AOO61e7wXXuHZ6xe7o9D3Ds9Yvd0eil3/wAd1q93m/8AjutXu8F17h2esXu6PQ9w7PWL3dHopd/8d1q93m/+O61e7wXXuHZ6xe7o9D3Ds9Yvd0eil3/x3Wr3eb/47rV7vBde4dnrF7uj0PcOz1i93R6KXf8Ax3Wr3eb/AOO61e7wXXuHZ6xe7o9D3Ds9Yvd0eil3/wAd1q93m/8AjutXu8F17h2esXu6PQ9w7PWL3dHopd/8d1q93r/RuOvY7C36r1yq5NNcRE1fLgBm8zwsYHML1mmqqqm3VsiZ45eCZqHnzFdvyhDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATdOc+4Xt+UoSbpzn3C9vykFxrzk2G7c+DNNLrzk2G7c+DNAAAAAAAAACRluU4jNrs02adu5/VVPBTT/dcW9BVTT8WKpiroi3tjxBnxaZnpPFZbbm5Tub9unjmiPij+3oq4nbAAADTaD5HiPyR4QzLTaD5HiPyR4QCl1Dz5iu35QhpmoefMV2/KEMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN05z7he35ShJunOfcL2/KQXGvOTYbtz4M00uvOTYbtz4M0AAAAAAA9MNh6sXibdmn9VyqKY+215p2mq6aM+wu64t1Mf3mmYgGnxF7D6XyiNzT8NHw00/Oupnr2sMddubqm5Rbp+VMUROzvWWvLdU4XD1f0U1zE/vMcHhLMg1em9T76XPY3qaab2zbTMcVceqq1dlVOXZhTct07m3iImdkfKqOPx8UfTdFVzPcNueOmqZn7RsnauNe10/wClw9P9U3JmP22cPjAMyAA02g+R4j8keEMy02g+R4j8keEApdQ8+Yrt+UIaZqHnzFdvyhDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATdOc+4Xt+UoSbpzn3C9vykFxrzk2G7c+DNNLrzk2G7c+DNAAAAAAAPtFyq1cpqpnc1UTFVM9Ew+ANpl+Pw+pstqorppmao2Xbc8dM/zilWXtBT7X/bxWyjoro2zH/vhUFm9Xh7sXLdVVuuniqpnZMLC3q7H26NntaavvNEbQaHKskw+nrFdyattWz47tfBsjyhmtQ5xvxj91Tt9jbjc0bfn0z/d447NMRmU/796q5EcVPFTH9kcAABptB8jxH5I8IZlptB8jxH5I8IBS6h58xXb8oQ0zUPPmK7flCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAm6c59wvb8pQk3TnPuF7flILjXnJsN258GaaXXnJsN258GaAAAAAAAAANrq3bqvXKaKKZqrqnZTTHHMtRlWkLNjA1U4mmLl69GyqY/o/b1BlRLzjJ7uTYrcV/Fbq/RXs4Ko9UQAABptB8jxH5I8IZlptB8jxH5I8IBS6h58xXb8oQ0zUPPmK7flCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAm6c59wvb8pQk3TnPuF7flILjXnJsN258GaaXXnJsN258GaAAABYZDkFzOr23hosUz8dfT9o+/gBkOQ3M6v8ADuqLFM/HX0/aPv4PbUmmpyuqb1mJqw88ccc2/wDC9zTNMPprAU0UU07rZst24+f86Xlp/UVGdWps3oppxGz4qdnw3I+3oDIurduq9cpoopmquqdlNMccyt9QaWuYK9FzC0VXLNydm4jhmiZ8ltp/T9GSWJvXppm/Mbaqp4rcdEeoGn9P28lsTevTTN+Y21VTxUR0R6qzNdZXasdT/pdkWbc/OP8Al/w8dSakqzWqbNmZpw1M8M/O7/j7KkG0sX8LqnLJiY3VNXBVTP6rdX8+bLZxk93JsVuK/it1for/AO0erzy7MbuVYqL1meHiqpnirjolrbF/C6pyyYmN1TV+qmf1W5/nzBixLzjJ7uTYrcV/FRV+ivZwVR6ogDTaD5HiPyR4QzLTaD5HiPyR4QCl1Dz5iu35QhpmoefMV2/KEMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN05z7he35ShJunOfcL2/KQXGvOTYbtz4M00uvOTYbtz4M0ACwyHILmdXts7aLFE/HX0/aPv4AZDkNzOb+3hpsUz8dfT9o+/g0eZ5nh9NYCmiimndbNlq3Hz/nSZnmeH01gKaKKad1s2WrcfP+dLIYvF3MdiKr16rdXKuOej7QBi8Xcx2IqvXqt1cq456PtH2cUV1WrlNVNU01UztiqOOJfAGv05qOnNrfs7mynEUxwx8q46Y9EbW8YqcLTuOS/wDk3PHt+W37M1RXVauU1U1VU1UztiY44lrdPahozmz7G9uYxERsqpniuR0x6AyIt9S6bnLK5vWYmcPVPDH059FQA98uzG7leKi9Zq2VcUxPFXHRLwAbSxfwuqcsmJjdU1cFVM/qt1fz5stnGTXcmxO4r+Kir9Ff/aPV55dmN3KsVF6zPxcU0zxVx0SsdQ6npzbDUWbVvc0TsqrmqOHb0R6gp2m0HyPEfkjwhmWm0HyPEfkjwgFLqHnzFdvyhDTNQ8+Yrt+UIYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACbpzn3C9vylCTdOc+4Xt+UguNecmw3bnwZppdecmw3bnwZoFhkOQ3M6vbeGixTPx19P2j7+DR5nmmH01gKaKKad1s2W7cfP+dKgyTVNzKMNVZqo9rb2TNuOLcz0fsr8Xi7mOxFV69VurlXHPR9oAxeLuY7EVXr1W6uVcc9H2j7PMAAAH2iuq1cpqpqqpqpnbExxxL4A12ntQ0ZzZ9je3MYiI2VUzxXI6Y9FRqTTU5XVN6zEzh6p4Y+nPoqaK6rVymqmqaaqZ2xMccS1untRUZza9je3NOIiOGn5XI6Y9AZEW2ptO703PbWeT3J2bnbw0T0fsqQAAGm0HyPEfkjwhmWm0HyPEfkjwgFLqHnzFdvyhDTNQ8+Yrt+UIYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACbpzn3C9vylCTdOc+4Xt+UguNecmw3bnwZppNfTsw2G7c+DM+0p6QdDn2lPSe0p6QdDn2lPSe0p6QdDn2lPSe0p6QdDn2lPSe0p6QdPtFdVq5TVTVNNVM7YmOOJce0p6T2lPSCVmWbX82u01Xqtu5jZERwRH/ANR3PtKek9pT0g6HPtKek9pT0g6abQfI8R+SPCGX9pT0tRoGduDxH5I8IBS6h58xXb8oQ0zUPPmK7flCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlZHfow2cYe5cqimimrbMz8uCUUBta8/wAvufqxFir93O/WWfWw3dDGANnv1ln1sN3Qb9ZZ9bDd0MYA2e/WWfWw3dBv1ln1sN3QxgDZ79ZZ9bDd0G/WWfWw3dDGANnv1ln1sN3Qb9ZZ9bDd0MYA2e/WWfWw3dBv1ln1sN3QxgDZ79ZZ9bDd0G/WWfWw3dDGANnv1ln1sN3Qb9ZZ9bDd0MYA2e/WWfWw3dDqjP8AL7cfDiLFP7MUAlZ1fpxOb4i5bqiqiqvbEx8+CEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//Z';

// export const ERRORS = {
//   fs: { title: 'خطای سنسور فریزر', subvalue: 'سنسور فریزر چک شود' },
//   rs: { title: 'خطای سنسور یخچال', subvalue: 'سنسور یخچال چک شود' },
//   ds: { title: 'خطای سنسور اواپراتور', subvalue: 'سنسور اواپراتور چک شود' },
//   as: { title: 'خطای سنسور محیطی', subvalue: 'سنسور محیطی چک شود' },
//   ef: { title: 'خطا در عملکرد فن', subvalue: 'فن چک شود' },
//   da: { title: 'خطا در عملکرد دمپر', subvalue: 'دمپر چک شود' },
//   cc: { title: 'خطای کارکرد یکسره کمپرسور', subvalue: 'کمپرسور چک شود' },
//   oe: { title: 'خطای نوسان برق', subvalue: 'نوسان برق چک شود' },
//   df: { title: 'خطای سنسور برفک فریزر', subvalue: 'برفک را در فریزر چک کنید' },
//   dr: { title: 'خطای سنسور برفک یخچال', subvalue: 'برفک را در یخچال چک کنید' },
//   is: { title: 'خطای سنسور یخساز', subvalue: 'یخساز چک شود' },
//   f1: { title: 'خطای فن یخچال', subvalue: 'فن یخچال چک شود' },
//   f2: { title: 'خطای فن فریزر', subvalue: 'فن فریزر چک شود' },
//   f3: { title: 'خطای فن کندانسور', subvalue: 'فن کندانسور چک شود' },
// };

export const ERRORS: DeviceErrorType = {
  fs: { title: 'خطای سنسور فریزر', subValue: 'سنسور فریزر چک شود' },
  rs: { title: 'خطای سنسور یخچال', subValue: 'سنسور یخچال چک شود' },
  df: { title: 'خطای سنسور اواپراتور', subValue: 'سنسور اواپراتور چک شود' },
  dr: { title: 'خطای سنسور یخچال', subValue: 'سنسور یخچال چک شود' },
  as: { title: 'خطای سنسور محیطی', subValue: 'سنسور محیطی چک شود' },
  ff: { title: 'خطا در عملکرد فن فریزر', subValue: 'فن فریزر چک شود' },
  dd: { title: 'خطا در عملکرد دمپر', subValue: 'دمپر چک شود' },
  cc: { title: 'خطای کارکرد یکسره کمپرسور', subValue: 'کمپرسور چک شود' },
  oe: { title: 'خطای نوسان برق', subValue: 'نوسان برق چک شود' },
  cf: { title: 'خطا در عملکرد فن کندانسور', subValue: 'فن  کندانسور چک شود' },
  rf: { title: 'خطا در عملکرد فن یخچال', subValue: 'فن  یخچال چک شود' },
  rdo: { title: 'خطا در درب یخچال', subValue: 'درب یخچال بیش از 1 دقیقه است که باز مانده' },
  fdo: { title: 'خطا در درب فریزر', subValue: 'درب فریزر بیش از 1 دقیقه است که باز مانده' },
  de: { title: 'خطا در ارتباط با نمایشگر', subValue: 'کابل رابط نمایشگر چک شود' },
  is: { title: 'خطا در یخساز', subValue: 'بخش یخساز چک شود' },
};

export type DeviceErrorType = {
  [key: string]: {
    title: string;
    subValue: string;
  };
};
